[package]
name = "proc-generics"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
template-quote = "0.3.1"
proc-macro2 = "*"

[dependencies.syn]
version = "2.0"
features = [ "full", "derive", "printing", "extra-traits", "visit-mut"]


